services:
  mongodb:
    build: ./mongodb # it moves to mongodb Dockerfile directory
    image: mamatar/mongodb:1.0.0 # docker build -t mamatar/mongodb:1.0.0
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
    - redis:/data
  mysql:
    build: ./mysql
    image: mamatar/mysql:1.0.0
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3
    environment: 
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    container_name: rabbitmq
    volumes:
    - rabbitmq:/var/lib/rabbitmq
  catalogue:
    build: ./catalogue
    image: mamatar/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  user:
    build: ./user
    image: mamatar/user:1.0.0
    container_name: user
    environment:
      MONGO: "true"                              # ← indented under environment
      MONGO_URL: "mongodb://mongodb:27017/users" # ← indented under environment
    depends_on:
    - mongodb
    - redis
  cart:
    build: ./cart
    image: mamatar/cart:1.0.0
    container_name: cart
    depends_on:
    - redis
    - catalogue
  shipping:
    build: ./shipping
    image: mamatar/shipping:1.0.0
    container_name: shipping
    depends_on:
    - mysql
    - cart
  payment:
    build: ./payment
    image: mamatar/payment:1.0.0
    container_name: payment
    environment:
      CART_HOST: "cart"
      CART_PORT: "8080"
      USER_HOST: "user"
      USER_PORT: "8080"
      AMQP_HOST: "rabbitmq"
      AMQP_USER: "roboshop"
      AMQP_PASS: "roboshop123"
    depends_on:
    - rabbitmq
    - cart
    - user
  frontend:
    build: ./frontend
    image: mamatar/frontend:1.0.0
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment
networks:
  default:
    driver: bridge
    name: roboshop
    external: false # if true, you need to create network manually\

volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:    
  
